name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pytest

      - name: Unit Tests
        run: |
          pytest --junitxml=pytest-results.xml > pytest-results.txt || true
          echo "### Pytest Results" >> $GITHUB_STEP_SUMMARY
          tail pytest-results.txt >> $GITHUB_STEP_SUMMARY

      - name: Upload PyTest Report
        uses: actions/upload-artifact@v4
        with:
          name: PyTest Report
          path: pylint-results.xml

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install pylint

      - name: Code Linting
        run: |
          echo "### Pylint Results" >> $GITHUB_STEP_SUMMARY
          pylint app/ --fail-under=8 --output-format=json > pylint-report.json || true >> $GITHUB_STEP_SUMMARY
