name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install pytest pylint

      - name: Unit Tests
        run: pytest --junitxml=pytest-report.xml || true

      - name: Convert Test Failures to GitHub Annotations
        if: failure()
        run: |
          pip install junit2html
          junit2html pytest-report.xml --report pytest-report.html
          echo "::error file=tests/,title=Test Failure::Some tests failed! Check the Actions tab."

      - name: Code Linting
        run: |
          pylint app/ --fail-under=8 --output-format=json > pylint-report.json
      
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: pylint-report.json
