name: Security

on:
  push:

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit

      - name: Static Security Scan (Bandit)
        run: |
          bandit -r ./app --severity-level high

      - name: Dependency Check Strict (pip-audit)
        if: github.ref == 'refs/heads/main'
        run: pip-audit --strict

      - name: Dependency Check (pip-audit)
        if: github.ref != 'refs/heads/main'
        continue-on-error: true
        run: pip-audit

      - name: Save pip-audit results
        run: pip-audit --output pip-audit-report.json --format json

      - name: Upload pip-audit report
        uses: actions/upload-artifact@v3
        with:
          name: pip-audit-report
          path: pip-audit-report.json

  # zap_scan:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Build & Run Application
  #       run: |
  #         docker build -t fastapi-app .
  #         docker run -d -p 80:80 --name fastapi-container fastapi-app
      
  #     - name: ZAP Scan
  #       uses: zaproxy/action-full-scan@v0.12.0
  #       with:
  #         target: "http://localhost:80"
  #         docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
  #         allow_issue_writing: false

  #     - name: Upload ZAP Report
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: zap-security-report
  #         path: zap-report.html

  #     - name: Stop and Remove Container
  #       run: docker stop fastapi-container && docker rm fastapi-container
